<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FlexLabs.EntityFrameworkCore.Upsert" Version="9.100.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\cccc1808.ProcessEngine.Model.MessageStream.EFCore\cccc1808.ProcessEngine.Model.MessageStream.EFCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstract\Components\" />
  </ItemGroup>

</Project>
